### ISSUE TITLE
Replace needed from  Octokit to {  Octokit }

### ISSUE THREAD

**Issue by natheeshsunway** [christian-korneck/delete-run-artifacts-action#9]
`[@octokit/rest] const Octokit = require("@octokit/rest") is deprecated. Use const { Octokit } = require("@octokit/rest") instead` geting warning.

**Comment by christian-korneck** [comment]
Thanks. Should be resolved now with [updated dependencies](https://github.com/christian-korneck/delete-run-artifacts-action/commit/a45689ea73ec3e963804f887cfe821a1895f442b).

(This was an issue in `@actions/github`, which has been [fixed](https://github.com/actions/toolkit/pull/332) since we last updated dependencies).
